"""made some changes

Revision ID: 64415a040d10
Revises: 
Create Date: 2022-09-01 22:05:46.432480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64415a040d10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('agreement', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'agreement')
    # ### end Alembic commands ###
