version: '3.9'
services:
  db:
    restart: always
    image: "postgres:15.0"
    container_name: db
    volumes:
      - ./db/:/var/lib/postgresql/data
    environment:
      # PGDATA: ${PGDATA}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432

  api:
    restart: always
    build: ./api
    container_name: api
    env_file:
      - .env
    command: bash -c "alembic stamp head && alembic upgrade head && uvicorn main:app --reload --workers 4 --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    depends_on: 
      - db
    volumes:
      - ./api:/api

  # front:
  #   restart: always
  #   build: ./frontend
  #   env_file:
  #     - .env
  #   # environment:
  #   #   API_URL: http://localhost:8000/api/v1
  #   volumes:
  #     - ./frontend:/app
  #   ports:
  #     - "3000:3000"
  #   command: [ "yarn" , "dev","--host","0.0.0.0"]

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./frontend:/var/www
    depends_on:
      # - front
      - api

    ports:
      - "80:80"

